### ISSUE TITLE
conflicting types for LTDC

### ISSUE THREAD

**Issue by epikao** [lvgl/lv_port_stm32h745i_disco#2]
Hello,

When I try to build this project/port, I get the following error:
![image](https://user-images.githubusercontent.com/26655950/187894403-68b674a5-56bf-4374-a1f4-0c20622acf3c.png)

Thank you

**Comment by ahmetalperenbulut** [comment]
Hello, 

Have you disabled auto generated code ? Check the readme file. You must comment out this functions. 

"
  BSP initialize necessary peripherals so we must disable the CubeMX generated codes.
  
  CubeMX integration with BSP
  Disable CubeMX generated Functions
  HAL_LTDC_MspInit, HAL_LTDC_MspDeInit, MX_LTDC_Init
  MX_DMA2D_Init, HAL_DMA2D_MspInit, HAL_DMA2D_MspDeInit
  MX_TIM8_Init, HAL_TIM_PWM_MspInit, HAL_TIM_MspPostInit, HAL_TIM_PWM_MspDeInit
  MX_I2C4_Init, HAL_I2C_MspInit, HAL_I2C_MspDeInit
  MX_QUADSPI_Init, HAL_QSPI_MspInit, HAL_QSPI_MspDeInit, QUADSPI_IRQHandler
  MX_MDMA_Init, MDMA_IRQHandler
  MX_FMC_Init, HAL_FMC_MspInit, HAL_FMC_MspDeInit
  HAL_SDRAM_MspInit, HAL_SDRAM_MspDeInit
  MX_GPIO_Init, EXTI2_IRQHandler

 "

**Comment by epikao** [comment]
> Have you disabled auto generated code ? Check the readme file. You must comment out this functions.

no, so this "comment out job" is related to stm32h7xx_hal_msp.c + main.c ? right? Or are there more/other files?

Thank you

**Comment by ahmetalperenbulut** [comment]
no more files. just 2 files you have said. 
https://github.com/lvgl/lv_port_stm32h745i_disco/blob/master/CM7/Core/Src/main.c
I commented out these files but cubeide regenerates these files.
